[program:lumen-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --queue=notifications --tries=3 --timeout=30
autostart=true
autorestart=true
startretries=3
user=root
numprocs=8
redirect_stderr=false
stdout_logfile=/var/log/supervisor/queue.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
environment=REDIS_HOST="redis_mailer",REDIS_PASSWORD="999",HOME="/var/www/html",USER="www-data"

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
startretries=3
user=root
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0